[package]
name = "sitemaps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
quick-xml = "0.31.0"
ureq = "2.9.6"
url = "2.5.0"
